ZavrsniProjekat/Models/Bill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniProjekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillItems = new HashSet<BillItem>();
        }

        public int BillId { get; set; }

        [DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public decimal Tax { get; set; }

        [Display(Name = "Total Price")]
        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal TotalPrice { get; set; }

        [Display(Name = "Time of Purchase")]       
        public System.DateTime TimeOfPurchase { get; set; }

        public string Buyer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Bill Items")]
        public virtual ICollection<BillItem> BillItems { get; set; }

        public decimal TotalTax()
        {
            return TotalPrice * Tax;
        }

        public decimal Subtotal()
        {
            return BillItems.Sum(m => m.Price);
        }
    }
}

ZavrsniProjekat/ViewModels/BillViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ZavrsniProjekat.Models;

namespace ZavrsniProjekat.ViewModels
{
    public class BillViewModel
    {
        public BillViewModel()
        {
            this.BillItems = new HashSet<BillItem>();
        }

        public int BillId { get; set; }

        [DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public decimal Tax { get; set; }

        [Display(Name = "Total Price")]
        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal TotalPrice { get; set; }

        [Display(Name = "Time of Purchase")]
        public System.DateTime TimeOfPurchase { get; set; }

        public string Buyer { get; set; }

        
        [Display(Name = "Bill Items")]
        public virtual ICollection<BillItem> BillItems { get; set; }

        public decimal TotalTax()
        {
            return TotalPrice * Tax;
        }

        public decimal Subtotal()
        {
            return BillItems.Sum(m => m.Price);
        }
    }
}

ZavrsniProjekat/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZavrsniProjekat.Infrastructure;
using ZavrsniProjekat.Models;
using ZavrsniProjekat.ViewModels;

namespace ZavrsniProjekat.Controllers
{
    [Authorize(Roles = RoleName.Admin)]
    public class BillsController : Controller
    {
        private FurnitureShopsEntities db = new FurnitureShopsEntities();

        // GET: Bills
        public ActionResult Index()
        {
            return View("BillsList");
        }

        public ActionResult Report()
        {
            ViewBag.Category = new SelectList(db.Categories, "Name", "Name");
            ViewBag.StartDate = new DateTime();
            ViewBag.EndDate = new DateTime();
            return View("FormSubmit");           
        }

        public ActionResult GenerateReport(string Category, DateTime StartDate, DateTime EndDate)
        {
            DateTime endDate = EndDate.AddDays(1);

            var result = (from item in db.BillItems
                          join bill in db.Bills on item.BillId equals bill.BillId
                          where bill.TimeOfPurchase >= StartDate.Date && bill.TimeOfPurchase <= endDate
                          && item.FurnitureCategory.Equals(Category)
                          group item by new { item.FurnitureShop, item.FurnitureCategory, item.Amount, item.Price } into g
                          let sumPrice = g.Sum(m => m.Price)
                          let sumAmount = g.Sum(m => m.Amount)
                          select new ReportViewModel
                          {
                              Category = g.Key.FurnitureCategory,
                              Shop = g.Key.FurnitureShop,
                              AmountSold = sumAmount,
                              Price = sumPrice + sumPrice * Tax.RegularTax,
                              
                          }).ToList();

            var report = result.GroupBy(d => d.Shop)
                        .Select(m => new ReportViewModel
                        {
                            Shop = m.First().Shop,
                            Category = m.First().Category,
                            AmountSold = m.Sum(c => c.AmountSold),
                            Price = m.Sum(c => c.Price),
                            StartDate = StartDate,
                            EndDate = EndDate
                        }).ToList();
            return View(report);
        }

        public ActionResult GetAllData()
        {
            List<Bill> lst = db.Bills.ToList();
            var subCategoryToReturn = lst.Select(s => new
            {
                s.BillId,
                s.Buyer,
                s.TimeOfPurchase,
                TotalTax = s.TotalTax(),
                s.TotalPrice,
                FurnitureShops = s.BillItems.Select(m => new
                {
                    Shop = m.FurnitureShop
                }),
                BillItems = s.BillItems.Select(m => new
                {
                    Item = m.Furniture
                }),
                Subtotal = s.Subtotal()
            });

            return this.Json(subCategoryToReturn, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
       
    }
}

ZavrsniProjekat/Views/Bills/Bill.cshtml
@model ZavrsniProjekat.ViewModels.BillViewModel

@{
    ViewBag.Title = "Order";
}

<h2>Your Order</h2>

@using (Html.BeginForm("CompletePurchase", "ShoppingCart"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Bill</h4>    

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Bill To")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Buyer)
        </dd>        
        <dt>
            @Html.DisplayNameFor(model => model.BillItems)
        </dt>        
        <dd>
            <table width="600" style="border-bottom: 1px solid black" class="table-striped table-responsive-sm">
                <tr style="border-bottom:2px solid black;border-top:2px solid black">
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Shop</th>                    
                    <th style="text-align:right;padding-right:30px">Price</th>
                </tr>
                @{var index = 0;}
                @foreach (var item in Model.BillItems)
                {
                    Html.Hidden("BillItems[" + index + "].Furniture", item.Furniture);
                    Html.Hidden("BillItems[" + index + "].Price", item.Price);
                    Html.Hidden("BillItems[" + index + "].Amount", item.Amount);
                    Html.Hidden("BillItems[" + index + "].FurnitureShop", item.FurnitureShop);
                    Html.Hidden("BillItems[" + index + "].FurnitureCategory", item.FurnitureCategory);
                    index++;
                    <tr>
                        <td>@item.Furniture</td>
                        <td>@item.Amount</td>
                        <td>@item.FurnitureShop</td>                       
                        <td align="right">@item.Price.ToString("c")</td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
    <table width="600" class="table-responsive-sm">
        <tr>
            <td width="350"></td>
            <th align="right">
                @Html.DisplayName("Subtotal")
            </th>
            <td align="right">
                @(Model.Subtotal().ToString("c"))
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <b>@Html.DisplayNameFor(model => model.Tax)</b> @Html.DisplayFor(model => model.Tax)
            </td>
            <td align="right">
                @((Model.TotalTax().ToString("c")))
            </td>
        </tr>
        <tr>
            <td></td>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <td align="right">
                @Html.DisplayFor(model => model.TotalPrice)
            </td>
        </tr>
    </table>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.TimeOfPurchase)
        </dt>
        <dd>
            @Model.TimeOfPurchase.ToString("dd.MM.yyyy. HH:mm:ss")
        </dd>
    </dl>
    <div class="form-group">
        <div class="col-md-offset-6 col-md-10">
            <button type="submit" class="btn btn-success" style="margin-left:18%;width:30%"><i class="fa fa-shopping-bag"></i> Buy</button>
        </div>
    </div>
</div>
}
    <p>
        @Html.ActionLink("Back to Cart", "Index")
    </p>

ZavrsniProjekat/Views/Bills/BillsList.cshtml
@model IEnumerable<ZavrsniProjekat.Models.Bill>

@{
    ViewBag.Title = "Index";
}

<h2>Bills</h2>

<p>Search Bills by <b>Date, Buyer,</b> or <b>Furniture Shop.</b></p>


<table id="Table" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Bill Id</th>
            <th>Buyer</th>
            <th>Date</th>
            <th>Time</th>
            <th>Subtotal</th>
            <th>Total Tax</th>
            <th>Total Price</th>
            <th>Items</th>
            <th>Furniture Shops</th>
        </tr>
    </thead>

</table>

<link href="~/Scripts/datatables.min.css" rel="stylesheet" />
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />

@section scripts{
    <script src="~/Scripts/datatables.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>

    <script>

        $(document).ready(function () {
            dataTable = $("#Table").DataTable({
                "ajax": {
                    "url": "/Bills/GetAllData/",
                    "type": "GET",
                    "datatype": "json",
                    "dataSrc": ""
                },
                "columns": [
                    { "data": "BillId", "searchable": false },
                    { "data": "Buyer" },
                    {
                        "data": "TimeOfPurchase", render: function (data) {
                            return moment(data).format("DD.MM.YYYY.")
                        }
                    },
                    {
                        "data": "TimeOfPurchase", "searchable": false, render: function (data) {
                            return moment(data).format("HH:mm:ss")
                        }
                    },
                    { "data": "Subtotal", "searchable": false, render: $.fn.dataTable.render.number('.', ',', 2, '', " Din.") },
                    { "data": "TotalTax", "searchable": false, render: $.fn.dataTable.render.number('.', ',', 2, '', " Din.") },

                    { "data": "TotalPrice", "searchable": false, render: $.fn.dataTable.render.number('.', ',', 2, '', " Din.") },
                    {
                        "data": "BillItems", "searchable": false, render: function (data) {
                            var str = "";
                            for (var i = 0; i < data.length; i++) {
                                str += data[i].Item + ", ";
                            }
                            return str.split(", ").join("<br/>");
                        }
                    },
                    {
                        "data": "FurnitureShops", render: function (data) {
                            var str = "";
                            for (var i = 0; i < data.length; i++) {
                                str += data[i].Shop + ", ";
                            }
                            return str.split(", ").join("<br/>");
                        }
                    },
                ],
                "language": {
                    "emptyTable": "No data found"
                },
                "responsive": "true"
            });

        });

    </script>
}

ZavrsniProjekat/Views/Bills/FormSubmit.cshtml
@model ZavrsniProjekat.Models.Bill

@{
    ViewBag.Title = "Report";
}

<h2>Generate Report for period</h2>


@using (Html.BeginForm("GenerateReport", "Bills"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Report</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Name", "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessage("Category", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("StartDate", "Start Date",
                htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("StartDate", new { htmlAttributes = new {@class = "form-control date-picker", Value = "", id = "StartDate"} })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("EndDate", "End Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("EndDate", new { htmlAttributes = new { @class = "form-control date-picker", Value = "", @id = "EndDate"} })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Home Page", "Index", "Home")
</div>

@Styles.Render("~/Content/themes/smoothness/jquery-ui-themes-1.12.1/jquery-ui.min.css")
@section Scripts {
    @Scripts.Render("~/Scripts/jquery-ui.min.js");
    <script>
        $(function () {
            $(".date-picker").datepicker({
                dateFormat: "dd/MM/yy",
                maxDate: "0"
            });
        });
    </script>
}

ZavrsniProjekat/Views/Bills/GenerateReport.cshtml
@using System.Linq
@model IEnumerable<ZavrsniProjekat.ViewModels.ReportViewModel>
@{
    ViewBag.Title = "Generated Report";
}

@if (Model.FirstOrDefault() != null)
{
<h4>
    Furniture of category <b>@Model.FirstOrDefault().Category</b>  sold in period between
                          <b>@Model.FirstOrDefault().StartDate.ToString("dd.MM.yyyy.")</b> and
                          <b>@Model.FirstOrDefault().EndDate.ToString("dd.MM.yyyy.")</b>
</h4><br />

    <table class="container table-bordered table-striped">
        <tr>
            <th>Shop</th>
            <th>Amount Sold</th>
            <th>Total Earnings</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Shop</td>
                <td>@item.AmountSold</td>
                <td>@string.Format("{0:c}", @item.Price)</td>
            </tr>
        }

    </table><br />

    <h5>Total earnings of all shops for a selected category: <b>@string.Format("{0:c}", @Model.Sum(m => m.Price))</b></h5><br />            
}
else
{
    <h4>No item of the selected category has been sold in that period.</h4><br />
}

    <div>
        @Html.ActionLink("Back", "Report")        
    </div>