ZavrsniProjekat/Controllers/FurnituresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZavrsniProjekat.Models;

namespace ZavrsniProjekat.Controllers
{
    [Authorize]
    public class FurnituresController : Controller
    {
        private FurnitureShopsEntities db = new FurnitureShopsEntities();

        // GET: Furnitures
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.Admin))
                return View("IndexAdmin");
            return View("IndexBuyer");
        }        

        // GET: Furnitures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Furniture furniture = db.Furnitures.Find(id);
            if (furniture == null)
            {
                return HttpNotFound();
            }
            return View(furniture);
        }

        // GET: Furnitures/Create
        public ActionResult Add()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            ViewBag.FurnitureShopId = new SelectList(db.FurnitureShops, "FurnitureShopId", "Name");
            return View();
        }

        // POST: Furnitures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Furniture furniture, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    furniture.PhotoType = image.ContentType;
                    furniture.Photo = new byte[image.ContentLength];
                    image.InputStream.Read(furniture.Photo, 0, image.ContentLength);
                }
                db.Furnitures.Add(furniture);
                db.SaveChanges();
                return Json(new { success = true, message = "Added Successfully" }, JsonRequestBehavior.AllowGet);
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", furniture.CategoryId);
            ViewBag.FurnitureShopId = new SelectList(db.FurnitureShops, "FurnitureShopId", "Name", furniture.FurnitureShopId);
            return View(furniture);
        }
                
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Furniture furniture = db.Furnitures.Find(id);
            if (furniture == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", furniture.CategoryId);
            ViewBag.FurnitureShopId = new SelectList(db.FurnitureShops, "FurnitureShopId", "Name", furniture.FurnitureShopId);
            return View(furniture);
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Furniture furniture, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image == null)
                {
                    db.Entry(furniture).State = EntityState.Modified;
                    db.Entry(furniture).Property(x => x.Photo).IsModified = false;                    
                }
                else
                {
                    furniture.PhotoType = image.ContentType;
                    furniture.Photo = new byte[image.ContentLength];
                    image.InputStream.Read(furniture.Photo, 0, image.ContentLength);
                    db.Entry(furniture).State = EntityState.Modified;
                }                
                db.SaveChanges();
                return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", furniture.CategoryId);
            ViewBag.FurnitureShopId = new SelectList(db.FurnitureShops, "FurnitureShopId", "Name", furniture.FurnitureShopId);
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Furniture furniture = db.Furnitures.Find(id);
            db.Furnitures.Remove(furniture);
            db.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //[AllowAnonymous]
        //public ActionResult GetImage(int FurnitureId)
        //{
        //    Furniture furniture = db.Furnitures.Find(FurnitureId);
        //    if (furniture.Photo != null && furniture.PhotoType != null)
        //    {
        //        return File(furniture.Photo, furniture.PhotoType);
        //    }
        //    else
        //    {
        //        return null;
        //    }
        //}

        [AllowAnonymous]
        public ActionResult GetDataFromShop(int id)
        {
            List<Furniture> lst = db.Furnitures.ToList();
            var subCategoryToReturn = lst.Where(m => m.FurnitureShopId == id).Select(s => new
            {
                s.FurnitureId,
                s.Name,
                Category = s.Category.Name,
                s.AmountInStore,
                s.Price,
                Photo = s.Photo != null ? Convert.ToBase64String(s.Photo) : null,
                s.PhotoType
            });

            return this.Json(subCategoryToReturn, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAllData()
        {
            List<Furniture> lst = db.Furnitures.ToList();
            var subCategoryToReturn = lst.Select(s => new
            {
                s.FurnitureId,
                s.Code,
                s.Name,
                s.CountryOfOrigin,
                s.YearMade,
                Category = s.Category.Name,
                FurnitureShop = s.FurnitureShop.Name,
                s.AmountInStore,
                s.Price,
                Photo = s.Photo != null ? Convert.ToBase64String(s.Photo) : null,
                s.PhotoType

            });

            return this.Json(subCategoryToReturn, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DoesCodeExist(string Code)
        {
            return Json(!db.Furnitures.Any(x => x.Code == Code), JsonRequestBehavior.AllowGet);
        }
    }
}

ZavrsniProjekat/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZavrsniProjekat.Models;

namespace ZavrsniProjekat.Controllers
{
    public class HomeController : Controller
    {
        private FurnitureShopsEntities db = new FurnitureShopsEntities();

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View("IndexAuth");
            }
            ViewBag.FurnitureShopId = new SelectList(db.FurnitureShops, "FurnitureShopId", "Name");
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ZavrsniProjekat/Views/Home/Index.cshtml
@model ZavrsniProjekat.Models.FurnitureShop

@{
    ViewBag.Title = "Interior Online";
}

<h2 class="">Interior Online</h2><br />

<div class="">
    <p>Welcome Guest. We are one of the biggest furniture webshops on the planet.</p>
    <p>
        Check out our offer from various furniture shops.<br />
        If you wish to make a purchase, please <a href="@Url.Action("LogIn", "Account")">log in</a> or <a href="@Url.Action("Register", "Account")">register</a>.
    </p>
</div>

@using (Html.BeginForm("GetDataFromShop", "Furnitures", FormMethod.Get, new { onchange = "LoadData()" }))
{
    <div class="form-group">
        @Html.LabelFor(model => model.FurnitureShopId, "Please select a Shop")
        <div>
            @Html.DropDownList("FurnitureShopId", null, "Select a shop", htmlAttributes: new { @id = "list", @class = "form-control btn btn-primary dropdown-toggle"})
            @Html.ValidationMessageFor(model => model.FurnitureShopId, "", new { @class = "text-danger" })
        </div>
    </div>
}

<table id="Table" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Amount in Store</th>
            <th>Price</th>
            <th>Photo</th>            
        </tr>
    </thead>
    <tbody></tbody>
</table>
<div class="d-flex justify-content-center">
    <div id="carouselExampleControls" class="carousel slide w-50" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#firstCarousel" data-slide-to="0"></li>
            <li data-target="#firstCarousel" data-slide-to="1" class="active"></li>
            <li data-target="#firstCarousel" data-slide-to="2"></li>
            <li data-target="#firstCarousel" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Content/Pictures/1.jpg" alt="Bedroom">
            </div>
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/Content/Pictures/2.jpg" alt="Living room">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Content/Pictures/3.jpg" alt="Bedroom">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Content/Pictures/4.jpg" alt="Kitchen">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<link href="~/Scripts/datatables.min.css" rel="stylesheet" />
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />

@section scripts{
    <script src="~/Scripts/datatables.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>

    <script>

        $('#Table').hide();
        function LoadData() {
            if ($('#list').val() == 0) {
                $('#Table').parents('div.dataTables_wrapper').first().hide();
                return;
            }
            $('#Table').show();
            dataTable = $("#Table").DataTable({
                "ajax": {
                    "url": "/Furnitures/GetDataFromShop/",
                    "data": { id: $('#list').val() },
                    "type": "GET",
                    "datatype": "json",
                    "dataSrc": ""
                },
                "columns": [
                    { "data": "Name" },
                    { "data": "Category" },
                    { "data": "AmountInStore" },
                    { "data": "Price", render: $.fn.dataTable.render.number('.', ',', 2, '', " Din.") },
                    {
                        data: { photo: "Photo", type: "PhotoType" }, "searchable": false, render: function (data) {
                            return "<div class='d-flex justify-content-center'>" +
                                "<img class='img-thumbnail' width='120' height='120' style='max-height:120px;max-width:none'" +
                                "src='data:" + data.PhotoType + ";base64," + data.Photo + "'" +
                                "alt='No Image'/></div > "
                        }
                    },
                ],
                "language": {
                    "emptyTable": "No data found"
                },
                "searching": false,
                "destroy": true
            });
        }
    </script>
}

ZavrsniProjekat/Views/Home/IndexAuth.cshtml
@using Microsoft.AspNet.Identity

@{
    /**/

    ViewBag.Title = "Interior Online";
}

<h2 class="">Interior Online</h2><br />

@if (Request.IsAuthenticated)
{
    if (User.IsInRole("Admin"))
    {
        <div class="">
            Hello admin @User.Identity.GetUserName(). <br />
        </div><br />
    }
    else
    {
        <div class="">
            Welcome @User.Identity.GetUserName(). <br />
            To start your shopping <a href="@Url.Action("Index", "Furnitures")">click here.</a>
        </div><br />
    }
} 

<div class="d-flex justify-content-center">
    <div id="carouselExampleControls" class="carousel slide w-50" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#firstCarousel" data-slide-to="0"></li>
            <li data-target="#firstCarousel" data-slide-to="1"></li>
            <li data-target="#firstCarousel" data-slide-to="2"></li>
            <li data-target="#firstCarousel" data-slide-to="3" class="active"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Content/Pictures/1.jpg" alt="Bedroom">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Content/Pictures/2.jpg" alt="Living room">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/Content/Pictures/3.jpg" alt="Bedroom">
            </div>
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/Content/Pictures/4.jpg" alt="Kitchen">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>